export const ROLE_CODES = {
  ADMIN: 'ADMIN',
  SUPPORT: 'SUPPORT',
  USER: 'USER',
} as const

export const PERMISSION_CODES = {
  KNOWLEDGE_VIEW: 'knowledge:view',
  TICKET_VIEW: 'ticket:view',
  SYSTEM_VIEW: 'system:view',
  KNOWLEDGE_ARTICLE_CREATE: 'knowledge:article:create',
  TICKET_ASSIGN: 'ticket:assign',
  SYSTEM_USER_MANAGE: 'system:user:manage',
  SYSTEM_ROLE_MANAGE: 'system:role:manage',
} as const

export const TICKET_OPERATOR_ROLE_CODES = [ROLE_CODES.ADMIN, ROLE_CODES.SUPPORT]
export const KNOWLEDGE_MANAGER_ROLE_CODES = [ROLE_CODES.ADMIN, ROLE_CODES.SUPPORT]
export const AI_CENTER_ROLE_CODES = [ROLE_CODES.ADMIN, ROLE_CODES.SUPPORT]
export const SYSTEM_ADMIN_ROLE_CODES = [ROLE_CODES.ADMIN]

export const TICKET_OPERATOR_PERMISSION_CODES = [PERMISSION_CODES.TICKET_ASSIGN]
export const KNOWLEDGE_MANAGER_PERMISSION_CODES = [PERMISSION_CODES.KNOWLEDGE_ARTICLE_CREATE]
export const SYSTEM_MANAGER_PERMISSION_CODES = [
  PERMISSION_CODES.SYSTEM_USER_MANAGE,
  PERMISSION_CODES.SYSTEM_ROLE_MANAGE,
]
